"""add thread_id to approval audits

Revision ID: 0433dad91de1
Revises: 5024eb8de2ca
Create Date: 2026-10-02 14:19:16.745318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0433dad91de1'
down_revision: Union[str, Sequence[str], None] = '5024eb8de2ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # 1. Add the column allowing NULL values initially
    op.add_column('approval_audits', sa.Column('thread_id', sa.String(length=255), nullable=True))
    
    # 2. Backfill existing records with a default value so they aren't NULL
    op.execute("UPDATE approval_audits SET thread_id = 'legacy_migration'")
    
    # 3. Alter the column to enforce NOT NULL constraints
    op.alter_column('approval_audits', 'thread_id', nullable=False)
    
    # 4. Add your index back safely (Alembic autogenerated this part)
    op.create_index('ix_approval_audits_thread_id', 'approval_audits', ['thread_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_approval_audits_thread_id'), table_name='approval_audits')
    op.drop_column('approval_audits', 'thread_id')
    # ### end Alembic commands ###
