"""create approval audits

Revision ID: 5024eb8de2ca
Revises: 8a652afecc12
Create Date: 2026-10-02 14:13:54.295614

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5024eb8de2ca'
down_revision: Union[str, Sequence[str], None] = '8a652afecc12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('approval_audits',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('requester_id', sa.Uuid(), nullable=False),
    sa.Column('approver_id', sa.Uuid(), nullable=False),
    sa.Column('approved', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['approver_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['requester_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approval_audits_approver_id'), 'approval_audits', ['approver_id'], unique=False)
    op.create_index(op.f('ix_approval_audits_requester_id'), 'approval_audits', ['requester_id'], unique=False)
    op.create_index(op.f('ix_approval_audits_tenant_id'), 'approval_audits', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_approval_audits_tenant_id'), table_name='approval_audits')
    op.drop_index(op.f('ix_approval_audits_requester_id'), table_name='approval_audits')
    op.drop_index(op.f('ix_approval_audits_approver_id'), table_name='approval_audits')
    op.drop_table('approval_audits')
    # ### end Alembic commands ###
