"""approval audits - make approver-id nullable

Revision ID: 698b5d0a92d2
Revises: 0433dad91de1
Create Date: 2026-10-02 14:46:49.961471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '698b5d0a92d2'
down_revision: Union[str, Sequence[str], None] = '0433dad91de1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('approval_audits', 'approver_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('approval_audits', 'approver_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
